# raven configuration
log_dir          = /home/flag06
max_size         = 10485760
retention_days   = 7
loglevel_pattern = ^(DEBUG|INFO|WARN|ERROR):
archive_dir      = /tmp/archiveCC
enable_archive    = 1
retention_days   = 7
dry_run = 0
enable_report = 1
report_dir = /tmp/repoters