#level06@snowcrash:/tmp/lll$ cat /etc/raven/raven.conf 
# raven configuration
log_dir         = /tmp/lll
archive_dir      = /tmp/wala/
max_size         = 100 #this must be adjusted base one how old the .flag could be 
retention_days   = 107
enable_archive   = 1
